version: "3.1"

services:
  php:
    image: siggib007/phpmysqli
    ports:
      - 8080:80
      - 9000:9000
    volumes:
      - ./:/var/www/html/
    environment:
      - MYSQL_HOST
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DB
      - KEYLESSID
      - KEYLESSKEY
      - KEYLESSUID
      - EMAILPORT
      - EMAILPWD
      - EMAILSERVER
      - EMAILUSER
      - USESSL
      - USESTARTTLS
      - XDEBUG_CONFIG
      - DopplerKEY
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
      - ./:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD

volumes:
  mysql-data: